site_name: MARS

site_url: https://marstmu.com/
site_description: MARS Website.
site_author: MARS
repo_url: https://github.com/marstmu/marswebsite
edit_uri: edit/main/docs/

copyright: mars.group@torontomu.ca

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  logo: img/logo-no-text.png
  favicon: img/favicon.ico
  features:
   # - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - navigation.instant
    - content.action.edit
    - content.code.copy
    - navigation.indexes
    - toc.follow
plugins:
  - exclude:
      glob:
        - '.*/**'  # Excludes all directories and files starting with a dot
        - '.*'     # Excludes all top-level files starting with a dot

  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     timezone: America/Toronto
  
  # - git-committers:
  #     repository: marstmu/marswebsite
  #     branch: main
  #     token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - blog:
      authors: true
  - search
  # - rss:
  #     match_path: blog/posts/.* 
  #     date_from_meta:
  #       as_creation: date

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  
extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marstmu/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mars.tmu/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/marstmu/?originalSubdomain=ca
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/BaQZkd2TKj


extra_css:
  - css/extra.css

