authors:
  zeul:
    name: Zeul Mordasiewicz
    description: co-captain
    avatar: https://avatars.githubusercontent.com/u/55005377
    url: https://github.com/zeulewan
  kolya:
    name: Nikolai
    description: co-captain
    avatar: https://avatars.githubusercontent.com/u/145951024
    url: https://github.com/nikolaisydorenko 
  Nate:
    name: Nathanael H
    description: Helper
    avatar: https://avatars.githubusercontent.com/u/128150666
    url: https://github.com/Nathanael-e-h
  Nathan:
    name: Nathan L
    description: PCB Lead
    avatar: https://avatars.githubusercontent.com/u/75654981
    url: https://github.com/Javezki
